### PR TITLE
feat: packaging and add netdata

### PR DESCRIPTION
**Pull request by Cruise-z**
real-time performance monitoring (metapackage).

Log: packaging and add netdata
Issue: deepin-community/sig-deepin-sysdev-team#226

### CODE REVIEW

**Review by UTsweetyfish — CHANGES_REQUESTED** [review]
软链接有问题。

```
./debian/missing-sources/gauge-1.3.2.js -> /persistent/home/zrz/Project/deb_pr/new2/ftest/netdata_1.40.1.orig/netdata-1.40.1/debian/missing-sources/gauge-1.3.2.js
./debian/netdata-core-no-sse.dirs -> /persistent/home/zrz/Project/deb_pr/new2/ftest/netdata_1.40.1.orig/netdata-1.40.1/debian/netdata-core-no-sse.dirs
./debian/netdata-core-no-sse.docs -> /persistent/home/zrz/Project/deb_pr/new2/ftest/netdata_1.40.1.orig/netdata-1.40.1/debian/netdata-core-no-sse.docs
./debian/netdata-core-no-sse.install -> /persistent/home/zrz/Project/deb_pr/new2/ftest/netdata_1.40.1.orig/netdata-1.40.1/debian/netdata-core-no-sse.install
./debian/netdata-core-no-sse.maintscript -> /persistent/home/zrz/Project/deb_pr/new2/ftest/netdata_1.40.1.orig/netdata-1.40.1/debian/netdata-core-no-sse.maintscript
./debian/netdata-core-no-sse.manpages -> /persistent/home/zrz/Project/deb_pr/new2/ftest/netdata_1.40.1.orig/netdata-1.40.1/debian/netdata-core-no-sse.manpages
./debian/netdata-core-no-sse.netdata.logrotate -> /persistent/home/zrz/Project/deb_pr/new2/ftest/netdata_1.40.1.orig/netdata-1.40.1/debian/netdata-core-no-sse.netdata.logrotate
./debian/netdata-core-no-sse.netdata.service -> /persistent/home/zrz/Project/deb_pr/new2/ftest/netdata_1.40.1.orig/netdata-1.40.1/debian/netdata-core-no-sse.netdata.service
./debian/netdata-core-no-sse.postinst -> /persistent/home/zrz/Project/deb_pr/new2/ftest/netdata_1.40.1.orig/netdata-1.40.1/debian/netdata-core-no-sse.postinst
./debian/netdata-core-no-sse.postrm -> /persistent/home/zrz/Project/deb_pr/new2/ftest/netdata_1.40.1.orig/netdata-1.40.1/debian/netdata-core-no-sse.postrm
./debian/netdata-core-no-sse.README.Debian -> /persistent/home/zrz/Project/deb_pr/new2/ftest/netdata_1.40.1.orig/netdata-1.40.1/debian/netdata-core-no-sse.README.Debian
./Dockerfile -> /persistent/home/zrz/Project/deb_pr/new2/ftest/netdata_1.40.1.orig/netdata-1.40.1/Dockerfile
./.dockerignore -> /persistent/home/zrz/Project/deb_pr/new2/ftest/netdata_1.40.1.orig/netdata-1.40.1/.dockerignore
./packaging/installer/kickstart-ng.sh -> /persistent/home/zrz/Project/deb_pr/new2/ftest/netdata_1.40.1.orig/netdata-1.40.1/packaging/installer/kickstart-ng.sh
./packaging/installer/kickstart-static64.sh -> /persistent/home/zrz/Project/deb_pr/new2/ftest/netdata_1.40.1.orig/netdata-1.40.1/packaging/installer/kickstart-static64.sh
./web/gui/dashboard/README.md -> /persistent/home/zrz/Project/deb_pr/new2/ftest/netdata_1.40.1.orig/netdata-1.40.1/web/gui/dashboard/README.md
```

**Comment by Cruise-z** [comment]
@Zeno-sole @chenchongbiao 这个包在本地构建时一开始缺少依赖，然后就在本机上装了该虚拟包和各种缺失依赖之后本地调试，可以正常构建，我看到有同学已经构建了这个包并且CI上已经发布，所以说在CI上的编译过程不存在缺失依赖的问题，但是在CI上就不知道犯了什么病导致makefile.am执行的时候找不到md文件（多返回了一个目录）：
Making all in dashboard
[   55s] make[6]: Entering directory '/usr/src/packages/BUILD/build-core/web/gui/dashboard'
[   55s] make[6]: *** No rule to make target '../../../../web/gui/dashboard/README.md', needed by 'all-am'.  Stop.
[   55s] make[6]: Leaving directory '/usr/src/packages/BUILD/build-core/web/gui/dashboard'

**Comment by Cruise-z** [comment]
> 软链接有问题。
> 
> ```
> ./debian/missing-sources/gauge-1.3.2.js -> /persistent/home/zrz/Project/deb_pr/new2/ftest/netdata_1.40.1.orig/netdata-1.40.1/debian/missing-sources/gauge-1.3.2.js
> ./debian/netdata-core-no-sse.dirs -> /persistent/home/zrz/Project/deb_pr/new2/ftest/netdata_1.40.1.orig/netdata-1.40.1/debian/netdata-core-no-sse.dirs
> ./debian/netdata-core-no-sse.docs -> /persistent/home/zrz/Project/deb_pr/new2/ftest/netdata_1.40.1.orig/netdata-1.40.1/debian/netdata-core-no-sse.docs
> ./debian/netdata-core-no-sse.install -> /persistent/home/zrz/Project/deb_pr/new2/ftest/netdata_1.40.1.orig/netdata-1.40.1/debian/netdata-core-no-sse.install
> ./debian/netdata-core-no-sse.maintscript -> /persistent/home/zrz/Project/deb_pr/new2/ftest/netdata_1.40.1.orig/netdata-1.40.1/debian/netdata-core-no-sse.maintscript
> ./debian/netdata-core-no-sse.manpages -> /persistent/home/zrz/Project/deb_pr/new2/ftest/netdata_1.40.1.orig/netdata-1.40.1/debian/netdata-core-no-sse.manpages
> ./debian/netdata-core-no-sse.netdata.logrotate -> /persistent/home/zrz/Project/deb_pr/new2/ftest/netdata_1.40.1.orig/netdata-1.40.1/debian/netdata-core-no-sse.netdata.logrotate
> ./debian/netdata-core-no-sse.netdata.service -> /persistent/home/zrz/Project/deb_pr/new2/ftest/netdata_1.40.1.orig/netdata-1.40.1/debian/netdata-core-no-sse.netdata.service
> ./debian/netdata-core-no-sse.postinst -> /persistent/home/zrz/Project/deb_pr/new2/ftest/netdata_1.40.1.orig/netdata-1.40.1/debian/netdata-core-no-sse.postinst
> ./debian/netdata-core-no-sse.postrm -> /persistent/home/zrz/Project/deb_pr/new2/ftest/netdata_1.40.1.orig/netdata-1.40.1/debian/netdata-core-no-sse.postrm
> ./debian/netdata-core-no-sse.README.Debian -> /persistent/home/zrz/Project/deb_pr/new2/ftest/netdata_1.40.1.orig/netdata-1.40.1/debian/netdata-core-no-sse.README.Debian
> ./Dockerfile -> /persistent/home/zrz/Project/deb_pr/new2/ftest/netdata_1.40.1.orig/netdata-1.40.1/Dockerfile
> ./.dockerignore -> /persistent/home/zrz/Project/deb_pr/new2/ftest/netdata_1.40.1.orig/netdata-1.40.1/.dockerignore
> ./packaging/installer/kickstart-ng.sh -> /persistent/home/zrz/Project/deb_pr/new2/ftest/netdata_1.40.1.orig/netdata-1.40.1/packaging/installer/kickstart-ng.sh
> ./packaging/installer/kickstart-static64.sh -> /persistent/home/zrz/Project/deb_pr/new2/ftest/netdata_1.40.1.orig/netdata-1.40.1/packaging/installer/kickstart-static64.sh
> ./web/gui/dashboard/README.md -> /persistent/home/zrz/Project/deb_pr/new2/ftest/netdata_1.40.1.orig/netdata-1.40.1/web/gui/dashboard/README.md
> ```

这个该怎么解决呢呜呜呜

**Comment by Cruise-z** [comment]
> 软链接有问题。
> 
> ```
> ./debian/missing-sources/gauge-1.3.2.js -> /persistent/home/zrz/Project/deb_pr/new2/ftest/netdata_1.40.1.orig/netdata-1.40.1/debian/missing-sources/gauge-1.3.2.js
> ./debian/netdata-core-no-sse.dirs -> /persistent/home/zrz/Project/deb_pr/new2/ftest/netdata_1.40.1.orig/netdata-1.40.1/debian/netdata-core-no-sse.dirs
> ./debian/netdata-core-no-sse.docs -> /persistent/home/zrz/Project/deb_pr/new2/ftest/netdata_1.40.1.orig/netdata-1.40.1/debian/netdata-core-no-sse.docs
> ./debian/netdata-core-no-sse.install -> /persistent/home/zrz/Project/deb_pr/new2/ftest/netdata_1.40.1.orig/netdata-1.40.1/debian/netdata-core-no-sse.install
> ./debian/netdata-core-no-sse.maintscript -> /persistent/home/zrz/Project/deb_pr/new2/ftest/netdata_1.40.1.orig/netdata-1.40.1/debian/netdata-core-no-sse.maintscript
> ./debian/netdata-core-no-sse.manpages -> /persistent/home/zrz/Project/deb_pr/new2/ftest/netdata_1.40.1.orig/netdata-1.40.1/debian/netdata-core-no-sse.manpages
> ./debian/netdata-core-no-sse.netdata.logrotate -> /persistent/home/zrz/Project/deb_pr/new2/ftest/netdata_1.40.1.orig/netdata-1.40.1/debian/netdata-core-no-sse.netdata.logrotate
> ./debian/netdata-core-no-sse.netdata.service -> /persistent/home/zrz/Project/deb_pr/new2/ftest/netdata_1.40.1.orig/netdata-1.40.1/debian/netdata-core-no-sse.netdata.service
> ./debian/netdata-core-no-sse.postinst -> /persistent/home/zrz/Project/deb_pr/new2/ftest/netdata_1.40.1.orig/netdata-1.40.1/debian/netdata-core-no-sse.postinst
> ./debian/netdata-core-no-sse.postrm -> /persistent/home/zrz/Project/deb_pr/new2/ftest/netdata_1.40.1.orig/netdata-1.40.1/debian/netdata-core-no-sse.postrm
> ./debian/netdata-core-no-sse.README.Debian -> /persistent/home/zrz/Project/deb_pr/new2/ftest/netdata_1.40.1.orig/netdata-1.40.1/debian/netdata-core-no-sse.README.Debian
> ./Dockerfile -> /persistent/home/zrz/Project/deb_pr/new2/ftest/netdata_1.40.1.orig/netdata-1.40.1/Dockerfile
> ./.dockerignore -> /persistent/home/zrz/Project/deb_pr/new2/ftest/netdata_1.40.1.orig/netdata-1.40.1/.dockerignore
> ./packaging/installer/kickstart-ng.sh -> /persistent/home/zrz/Project/deb_pr/new2/ftest/netdata_1.40.1.orig/netdata-1.40.1/packaging/installer/kickstart-ng.sh
> ./packaging/installer/kickstart-static64.sh -> /persistent/home/zrz/Project/deb_pr/new2/ftest/netdata_1.40.1.orig/netdata-1.40.1/packaging/installer/kickstart-static64.sh
> ./web/gui/dashboard/README.md -> /persistent/home/zrz/Project/deb_pr/new2/ftest/netdata_1.40.1.orig/netdata-1.40.1/web/gui/dashboard/README.md
> ```

已找到问题所在，感谢老师！学到了学到了

**Comment by Cruise-z** [comment]
由于此次更新代码后未进行CI测试，所以关闭此pr,新建一个pr检测能否build成功。

**Pull request closed without merging**
